In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from bokeh.plotting import figure,show
from bokeh.models import ColumnDataSource
from bokeh.models import HoverTool
import warnings
warnings.filterwarnings('ignore') 
import os 
import time

In [13]:
per_sum = [x for x in range(1,101)]
fortune1 = fortune2 = fortune3 = pd.DataFrame([100 for i in range(100)],index=per_sum)


fortune2

       0
1    100
2    100
3    100
4    100
5    100
6    100
7    100
8    100
9    100
10   100
11   100
12   100
13   100
14   100
15   100
16   100
17   100
18   100
19   100
20   100
21   100
22   100
23   100
24   100
25   100
26   100
27   100
28   100
29   100
30   100
..   ...
71   100
72   100
73   100
74   100
75   100
76   100
77   100
78   100
79   100
80   100
81   100
82   100
83   100
84   100
85   100
86   100
87   100
88   100
89   100
90   100
91   100
92   100
93   100
94   100
95   100
96   100
97   100
98   100
99   100
100  100

[100 rows x 1 columns]